#pragma once
#include <WinUser.h>

enum WindowCodes {
	APP_WC_SHOW = WM_APP + 1,
	APP_WC_SYSTEMTRAY,
	APP_WC_CONSOLE,

	APP_SHOW_COPY,
	APP_SHOW_PASTE,
	APP_SHOW_BANK,
	APP_SHOW_EXPORT,
	APP_SHOW_TAB,
	APP_SHOW_SEMICOLON,
	APP_SHOW_PAUSED,
	APP_SHOW_DELAY
};